### ISSUE TITLE
Detect code in private constructor for utility classes and suggest the removal

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#116]
### What it does

A private constructor can only be called from inside a class. This is used to prevent the
instantiation of a class which only has static methods.

Some IDEs add a `throw Exception` inside the private constructor. That code is there to prevent
someone from calling the constructor through reflections (even though it is private), but this is
unnecessary here. It will just result in more code, might introduce other mistakes like having a bad constant name for the exception message at the top of the class.

What needs to be considered:
- the private constructor must not be called from anywhere inside the class (for example in a factory method)

### Lint Name

UNREACHABLE_CODE

### Category

complexity

### Example

```java
class Utils {
    private Utils() {
        throw new AssertionError("do not call me");
    }
}
```

Could be written as:

```java
class Utils {
    private Utils() {
    }
}
```

**Comment by Feuermagier** [comment]
I know you already implemented the check, but at least with our lecture throws in those constructors are fine, and actually wanted (though not required)
