### ISSUE TITLE
Leaking mutable attributes without copying them

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#20]
For example
```java
class A {
    private List<String> myList;
    
    public List<String> getList() {
        return this.myList;
    }
}
```
instead of
```java
class A {
    private List<String> myList;
    
    public List<String> getList() {
        return new ArrayList<>(this.myList);
    }
}
```

Same problem with
```java
class A {
    private List<String> myList;
    
    public void setList(List<String> myList) {
        this.myList = myList;
    }
}
```

**Comment by Feuermagier** [comment]
Getters should already be covered by [oop.ListGettersSettersCheck](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/oop/ListGetterSetterCheck.java) (despite its name the check is not yet capable of working with setters). Scenarios were attributes are immutable lists (such as from List.of(...)) are also covered.
