### ISSUE TITLE
Detect multithreading specific stuff

### ISSUE THREAD

**Issue by Feuermagier** [Feuermagier/autograder#204]
### What it does

Very rarely students try to make their code thread safe, even though they never use threads. For the start and given the rare occurrence of this issue it would be enough to simply detect synchronized blocks and methods that are explicitly synchronized.

### Lint Name

MultiThreadingConstructs

### Category

complexity

### Example

```java
synchronized (this) {
    // ...
}
```

**Comment by Luro02** [comment]
Should be trivial to implement:
1. Write a `CtScanner` like for [`api.CommonReimplementation`](https://github.com/Feuermagier/autograder/blob/e7eff25b75b7ef5a6e0a6c8bd0e6bce7c4421d30/autograder-core/src/main/java/de/firemage/autograder/core/check/api/CommonReimplementation.java#L121-L133)
2. Visit all [`CtSynchronized`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/code/CtSynchronized.html) and for each one that has a valid source position and is not implicit, emit an annotation
3. Visit all [`CtModifiable`](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/declaration/CtModifiable.html) and for each one that has a valid source position and is not implicit and `isSynchronized` is true, emit an annotation

Optionally: One could limit the `SourcePosition` by annotating the `expression` in `synchronized (expression) { ... }` and for the `CtModifiable` one could get the position of the synchronized keyword with `getExtendedModifiers()`
