### ISSUE TITLE
`RuntimeExceptionCatchCheck`: Should not trigger for catching `NumberFormatException` or exceptions that have been thrown in Lambdas

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#27]
In both cases, one has no other option, except for catching/rethrowing as a checked exception.

**Comment by Feuermagier** [comment]
Did you observe your issue regarding the NFE in practice? Because if I'm not mistaken the lint shoudn't trigger for NFEs.

Regarding lambdas, I think our policy is that students shouldn't use lambdas if this would require catching unchecked exceptions.

**Comment by Luro02** [comment]
I did not observe it yet

**Comment by Feuermagier** [comment]
Okay, I've added a test that validates this behavior. I'll close this issue, because even if we would accept catching runtime exceptions thrown in lambdas, I don't think we could detect the origin of a possible runtime exception statically.
