### ISSUE TITLE
Autograder creates a simplify return annotation in main Method.

### ISSUE THREAD

**Issue by ProgramPhoenix** [Feuermagier/autograder#314]
### Summary

The Autograder creates the following Message: `Die Variable 'end' ist unnötig, returne stattdessen den Wert: 'return (((word1 + separator) + word2) + separator) + word3'.` in a main Method with a `System.out` at the end and not with an return statement.

### Lint Name

unnecessary complexity (small)

### Reproducer

```java
[...]
String end = word1 + separator + word2 + separator + word3;
System.out.println(end);
```

**Comment by Luro02** [comment]
Is it not fixed with the latest version? https://github.com/Feuermagier/autograder/commit/2e005274508d1d0c27acce461a1964bbd6dcd269

**Comment by Luro02** [comment]
I will publish a new release now

**Comment by Luro02** [comment]
Should be solved with the latest release.
