### ISSUE TITLE
`AVOID_SHADOWING` should not report setter parameters

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#327]
### Summary

I think it is fine to allow this for setter. The problem is how could a setter be detected?
Maybe allow shadowing in parameters? Will this make the lint useless? Or maybe one could check if both `this.value` and `value` is read in the method and only then emit the lint?

### Lint Name

AVOID_SHADOWING

### Reproducer

```java
public void setValue(int value) {
    this.value = value;
}
```

**Comment by Feuermagier** [comment]
There's already a method isSetter in SpoonUtil, though it could probably be improved

**Comment by Luro02** [comment]
I am thinking of implementing this part.
> Or maybe one could check if both this.value and value is read in the method and only then emit the lint?

Should be trivial to search for two `CtVariableRead` in a method. This would limit bloat as well, because it would only detect the really bad cases, where shadowing is confusing.
