### ISSUE TITLE
Maybe slim down the Autograder

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#340]
### Description

The autograder has a lot of dependencies, but most of them are only used for a few things or not at all.

For example the following could be removed:
- lombok
- docker (move runtime features to a different module from core)
- spotbugs
- (maybe) pmd (there are two difficult to reimplement checks: https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/complexity/DiamondOperatorCheck.java and https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/general/ForToForEachCheck.java)
- jgraph
- autograder-treeg (currently unused?)
- errorprone (in my opinion not worth it)
- commons-compress? (not sure what it is even used for)
- lingua (might be removed as well)

The idea is to refactor those out of autograder-core and move them into a new module like autograder-extra. This module can then be included or not depending on the requirements.

**Comment by Feuermagier** [comment]
treeg is used by the Regex check - it is a parser for Regex. jgraph is currently unused and only an artifact from experimenting with graph-based analysis to detect UI/logic mixups. Commons-compress is probably also unused and only an artifact from when the Autograder was intended to be a web-based tool, where code was compressed for transfer.
