### ISSUE TITLE
Doesn't recognize unnecessary else

### ISSUE THREAD

**Issue by emiliafrey** [Feuermagier/autograder#369]
### Summary

<img width="247" alt="image" src="https://github.com/Feuermagier/autograder/assets/151136655/195b3d94-c0d0-483e-b2f0-0098f6af859b">

### Lint Name

das grün markierte ist überflüssig, habe ich aber selber erkannt, nicht der Autograder
_No response_

### Reproducer

```java
<code>
```

**Comment by Luro02** [comment]
Wie sollte der Code stattdessen aussehen?

Meinst du so?
```java
if (days <= 0) {
    return false;
} else if (day + days <= maxDay) {
    day += days;
    return true;
}

return false;
```
In dem Fall könnte man das auch so schreiben
```java
if (days <= 0) {
    return false;
} 

if (day + days <= maxDay) {
    day += days;
    return true;
}

return false;
```

Oder meinst du man sollte das machen?


```java
if (day <= 0 || !(day + days <= maxDay)) { // = day <= 0 || day + days > maxDay
    return false;
} else {
    day += days;
    return true;
}
```

**Comment by emiliafrey** [comment]
Else if würde ich schon behalten... intuitiv habe ich an das Erste gedacht
