### ISSUE TITLE
Advices method formatted() for class java.util.Locale

### ISSUE THREAD

**Issue by Fenmore** [Feuermagier/autograder#384]
### Summary

Using a Locale with string format results in the advice to use 'Locale.ENGLISH.formatted("%f", price)' instead, even though this method doesn't exist in the class java.util.Locale.

### Lint Name

USE_STRING_FORMATTED

### Reproducer

```java
import java.util.Locale;

public class Formatter {

    public static String formatPrice(double price) {
        return String.format(Locale.ENGLISH, "%f", price);
    }
}
```

**Comment by Luro02** [comment]
Duplicate of #380
