### ISSUE TITLE
Emit lint when only `equals`, but not `hashCode` is overwritten.

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#43]
Sometimes one overwrites `equals`, but not `hashCode`, which is not okay.

**Comment by libaurea** [comment]
The contract between [`equals`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Object.html#equals(java.lang.Object)) & [`hashCode`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Object.html#hashCode()) should be enforced in both directions. If one is implemented/overridden, the other should be too.
