### ISSUE TITLE
Misleading custom comment message for explicit type argument in diamond operators

### ISSUE THREAD

**Issue by Fenmore** [Feuermagier/autograder#44]
The line 
`this.stringTerrainInputList = new ArrayList<String>();`
created the custom comment "Verwende den 'diamond operator'" ("Use the 'diamond operator'"), but should have been "Explizite Typangabe 'String' kann mit <> ersetzt werden" ("Explicit type argument 'String' can be replaced with <>") (text copied from IntelliJ).

**Comment by Luro02** [comment]
This lint has been implemented by @Feuermagier as a PMD Check, I do not know if you are able to get the generics from inside the `<>` for the error message. This requires rewriting the lint as an integrated check to get a better error message. For now I have changed the error message to
> Du kannst die Typen in `< A, B, ... >` entfernen und stattdessen `<>` verwenden, siehe https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html und https://stackoverflow.com/a/16352848/7766117

This is of course not perfect but might do until the lint is reimplemented.

**Comment by Luro02** [comment]
Reimplementing this lint is very complicated and PMD itself does not provide enought context to replicate the message. It would be possible to write `Explicit type argument can be replaced with <>`, but this is a worse error message than the current one.
