### ISSUE TITLE
False-positive static variables that need to be static

### ISSUE THREAD

**Issue by c0derMo** [Feuermagier/autograder#54]
I've had an assignment with the following code example (paraphrased):

```java
public class Test {
    private static boolean someVariable = false;

    public static void main(String[] args) {
        for (int i = 0; i < 50; i++) {
            someVariable = someOtherMethodThatReturnsABoolean();
        }
    }
}
```

The variable declaration got annotated saying it should be an instance attribute, however, because the static main method uses the variable, it needs to be static from my understanding.

**Comment by Feuermagier** [comment]
The annotation looks right to me - mutable static state is generally discouraged. In this case the content of the main method should be executed in a non-static context.
