### ISSUE TITLE
Rewrite messages to make them more professional

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#632]
### Summary

They should not
- [ ] link to external sites, standalone
- [ ] explicitly address the user
- [ ] reference external things

### Current Message

.

### Reproducer

```java
<code>
```

**Comment by Feuermagier** [comment]
- Should we directly address the user (i.e. "Verwende X statt Y" or "Hier solltest du Z tun"), or indirectly ("man sollte A nicht tun")? I would prefer the former. 
- How long should messages be? At most a single sentence, or a short paragraph (if necessary)? 
- Do we want to explain reasons for annotations (a non-obvious annotation I just saw are tri-state optionals and wrapped Booleans)?
- Do we want links to the Wiki? I would prefer to add such links only in Artemis4J/Intelligrade
