### ISSUE TITLE
Improvements to Javadoc lint

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#7]
- [x] `@author` and `@version` should not be in method/attribute javadoc
- [x] `@author` with something that is not a u-shorthand
- [ ] `TODO`s in javadocs are not detected:
```java
/**
 * TODO Write Javadoc
 * 
 * @author uxxxx
 * @version 1.0
 */
```
- [ ] faulty javadoc prevents lints from triggering:
```java
/**
 *
 */
 */

/**
 *
/*
 */
 */

/*
 *
 */
```

**Comment by Feuermagier** [comment]
The u-shorthand is already detected by the AuthorTagCheck. I'll look into the other issues. Regarding the faulty Javadoc, I gues it's time to use @I-Al-Istannen's javadoc parser...

**Comment by I-Al-Istannen** [comment]
I mean, the first two are *syntax errors* and the last one is a normal comment, I am not sure I understand what you want to fix exactly.

**Comment by Feuermagier** [comment]
Yes, but I have seen student submissions that use normal block comments instead of Javadoc comments (but use Javadoc tags inside them), so we could try to give them feedback on those comments. My current idea is to apply your Javadoc parser to the block comment of a type/method if no (non-trivial) Javadoc comment exists.

**Comment by I-Al-Istannen** [comment]
That should work, yea. You might need to trick it by appending a second `*` at the beginning though :P I think it expects `/**`.

**Comment by Luro02** [comment]
> I mean, the first two are _syntax errors_ and the last one is a normal comment, I am not sure I understand what you want to fix exactly.

Oh, I am sorry! I made a mistake when copying over my notes.
The real-world example that I encountered was:
```java
/*
/* @author uxxxx
 * @version 1.0
 */
```
and with the second one I meant
```java
/**
/* @author uxxxx
 * @version 1.0
 */
```

There are people who mix up Javadoc and normal block comments.
It would be nice if the code could detect any malformed javadoc and give
a helpful suggestion about what the problem is. I consider anything malformed
that is not of the form:
```java
/**
 * <here a brief description>
 *
 * <optional extra detailed description>
 * @tag abc 123
 * ....
 */
```

I can remember the following problems:
- [ ] missing extra `*` (`/*` instead of `/**`)
- [ ] cursed whitespace:
```java
/**
* abc
   */
```
- [ ] Javadoc in places where it does not belong, like inside methods as a replacement for normal code

I am not sure how much of that is covered by checkstyle.
