### ISSUE TITLE
false-negative: `if ( !(a == b) )` is not linted

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#9]
```java
if (!(a == b)) {
}
```
can be written as
```java
if (a != b) {
}
```

**Comment by Feuermagier** [comment]
This is now covered by [8cf0b04](https://github.com/Feuermagier/autograder/commit/8cf0b04f690d6a119e0c4e057aa9ff3da6e06424) in [RedundantNegationCheck](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/complexity/RedundantNegationCheck.java)
