### ISSUE TITLE
Descriptive name checks should trigger on variables/attributes that contain the type

### ISSUE THREAD

**Issue by libaurea** [Feuermagier/autograder#98]
```java
List<T> exampleList;
int[] exampleIntArray;

// instead of

List<T> example;
int[] example;
```

**Comment by Luro02** [comment]
This could cause problems with variables that are named like the class.

For example in a `fromString(String string)` function, it makes sense to name the argument `string`.

I can think of two options:
- ignore variables where the type name is equal to the variable name
- try to remove the type name from the variable and then accept it if the resulting string is empty
